# Generated by Django 4.0 on 2022-01-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_brand_name_product_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
