# Generated by Django 4.0 on 2022-11-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_bar_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfilterattributes',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filter_attributes_sub_category', to='product.subcategory'),
        ),
        migrations.AddField(
            model_name='categoryfilterattributes',
            name='sub_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filter_attributes_sub_sub_category', to='product.subsubcategory'),
        ),
        migrations.AlterField(
            model_name='categoryfilterattributes',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filter_attributes_attribute', to='product.attribute'),
        ),
        migrations.AlterField(
            model_name='categoryfilterattributes',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filter_attributes_category', to='product.category'),
        ),
    ]
