# Generated by Django 4.0 on 2022-11-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_categoryfilterattributes_sub_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryFilterAttributes',
            new_name='FilterAttributes',
        ),
        migrations.AlterModelOptions(
            name='filterattributes',
            options={'verbose_name': 'FilterAttribute', 'verbose_name_plural': 'FilterAttributes'},
        ),
        migrations.AlterModelTable(
            name='filterattributes',
            table='filter_attributes',
        ),
    ]
