# Generated by Django 4.0 on 2022-01-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='title',
            new_name='name',
        ),
    ]
