# Generated by Django 4.0 on 2022-11-24 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_categoryfilterattributes_filterattributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterattributes',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filter_attributes_attribute', to='product.attribute'),
        ),
    ]
