# Generated by Django 4.0 on 2022-11-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_filterattributes_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
