# Generated by Django 4.0 on 2022-01-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_colors_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='Sizes',
        ),
    ]
