# Generated by Django 4.0 on 2022-11-27 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_category_cover_remove_category_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFilterAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('filter_attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_filter_attributes_filter_attribute', to='product.filterattributes')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_filter_attributes_product', to='product.product')),
            ],
            options={
                'verbose_name': 'ProductFilterAttribute',
                'verbose_name_plural': 'ProductFilterAttributes',
                'db_table': 'product_filter_attributes',
            },
        ),
    ]
