# Generated by Django 4.0 on 2022-11-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productfilterattributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.FloatField(default=0, help_text='Old price', max_length=255),
        ),
    ]
