# Generated by Django 4.0 on 2022-12-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pc_builder',
            field=models.BooleanField(default=False),
        ),
    ]
