# Generated by Django 4.0 on 2022-01-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productsizes_delete_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
