# Generated by Django 4.0 on 2022-01-16 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_tags_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='products')),
                ('status', models.CharField(choices=[('IN_QUEUE', 'In_Queue'), ('IN_PROCESSING', 'In_Processing'), ('COMPLETE', 'Complete')], max_length=20)),
                ('image_type', models.CharField(blank=True, choices=[('THUMBNAIL', 'Thumbnail'), ('COVER', 'Cover'), ('GENERAl', 'General')], max_length=50, null=True)),
                ('video_type', models.CharField(blank=True, choices=[('UPDATE', 'Update'), ('THANK_YOU', 'Thank you')], max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_media', to='product.product')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'db_table': 'media',
            },
        ),
    ]
