# Generated by Django 4.0 on 2022-12-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_whole_sale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_average_rating_number',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
