# Generated by Django 4.0 on 2022-01-18 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_productmedia_image_type_product_cover_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmedia',
            options={'verbose_name': 'ProductMedia', 'verbose_name_plural': 'ProductMedia'},
        ),
        migrations.AlterModelTable(
            name='productmedia',
            table='ProductMedia',
        ),
    ]
