# Generated by Django 4.0 on 2022-12-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_total_average_rating_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating_number',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
