# Generated by Django 4.0 on 2022-01-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_productmedia_options_alter_productmedia_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productmedia',
            table='productMedia',
        ),
    ]
