# Generated by Django 4.0 on 2022-12-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_category_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='pc_builder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='pc_builder',
            field=models.BooleanField(default=False),
        ),
    ]
