# Generated by Django 4.0 on 2022-01-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_productsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='', max_length=800),
        ),
    ]
