# Generated by Django 4.0 on 2022-12-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_subcategory_icon_subsubcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfilterattributes',
            name='attribute_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_filter_attributes_attribute_value', to='product.attributevalues'),
        ),
        migrations.AlterField(
            model_name='productfilterattributes',
            name='filter_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_filter_attributes_filter_attribute', to='product.filterattributes'),
        ),
    ]
