# Generated by Django 4.0 on 2022-02-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_product_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_sub_category', to='product.productsubcategory')),
            ],
            options={
                'verbose_name': 'ProductChildCategory',
                'verbose_name_plural': 'ProductChildCategories',
                'db_table': 'productChildCategory',
            },
        ),
    ]
