# Generated by Django 4.0 on 2022-12-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productfilterattributes_attribute_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_gaming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_gaming',
            field=models.BooleanField(default=False),
        ),
    ]
