# Generated by Django 4.0 on 2022-02-08 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customerprofile_options_and_more'),
        ('product', '0019_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tag_create_user', to='user.user'),
        ),
    ]
