# Generated by Django 4.0 on 2022-02-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_tags_created_by'),
        ('product', '0020_productchildcategory'),
    ]

    operations = [
    ]
