# Generated by Django 4.0 on 2022-12-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_category_is_gaming_product_is_gaming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_gaming',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_gaming',
        ),
    ]
