# Generated by Django 4.0 on 2023-01-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_category_is_gaming_remove_product_is_gaming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcombinationmedia',
            name='product_combination',
        ),
    ]
