# Generated by Django 4.0 on 2022-02-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0003_vendorrequest_is_verified'),
        ('product', '0021_merge_20220213_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cover',
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='product_vendor', to='vendor.vendor'),
        ),
    ]
