# Generated by Django 4.0 on 2023-01-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_productcombinationmedia_product_combination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcombinationsvariants',
            name='product_combination',
        ),
    ]
