# Generated by Django 4.0 on 2022-02-14 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0003_vendorrequest_is_verified'),
        ('product', '0022_remove_product_cover_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_vendor', to='vendor.vendor'),
        ),
    ]
