# Generated by Django 4.0 on 2022-02-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
