# Generated by Django 4.0 on 2023-01-04 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_productcombinationsvariants_product_combination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCombinations',
        ),
    ]
