# Generated by Django 4.0 on 2023-01-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_delete_productcombinations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCombinationsVariants',
        ),
    ]
