# Generated by Django 4.0 on 2022-02-20 05:00

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(upload_to='products', validators=[product.models.ProductMedia.validate_file_extension]),
        ),
    ]
