# Generated by Django 4.0 on 2023-01-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_delete_productcombinationsvariants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryVariation',
        ),
    ]
