# Generated by Django 4.0 on 2022-02-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
