# Generated by Django 4.0 on 2022-02-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_product_sell_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='product_category'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='product_category'),
        ),
    ]
