# Generated by Django 4.0 on 2023-01-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_delete_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAttributeValues',
        ),
    ]
