# Generated by Django 4.0 on 2022-02-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='rating_number',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='review_text',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
        migrations.AddField(
            model_name='productreview',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
