# Generated by Django 4.0 on 2023-01-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_delete_productattributevalues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAttributes',
        ),
    ]
