# Generated by Django 4.0 on 2023-01-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_category_is_gaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_gaming',
            field=models.BooleanField(default=False),
        ),
    ]
