# Generated by Django 4.0 on 2022-02-23 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_subscription'),
        ('product', '0031_productreview_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='name',
        ),
        migrations.AddField(
            model_name='productreview',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_product_review', to='user.customerprofile'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='rating_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_product_review', to='user.user'),
        ),
    ]
