# Generated by Django 4.0 on 2022-02-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_remove_productreview_name_productreview_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='rating_number',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='review_text',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
    ]
