# Generated by Django 4.0 on 2023-01-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_warranty_productwarranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwarranty',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productwarranty',
            name='warranty',
        ),
    ]
