# Generated by Django 4.0 on 2023-01-10 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_role'),
        ('product', '0035_productwarranty_product_productwarranty_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=300)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='save_pc_user', to='user.user')),
            ],
            options={
                'verbose_name': 'SavePc',
                'verbose_name_plural': 'SavePcs',
                'db_table': 'save_pc',
            },
        ),
    ]
