# Generated by Django 4.0 on 2023-01-10 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_savepc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePcItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='save_pc_items_category', to='product.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='save_pc_items_product', to='product.product')),
                ('save_pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_pc_items_save_pc', to='product.savepc')),
            ],
            options={
                'verbose_name': 'SavePcItems',
                'verbose_name_plural': 'SavePcItems',
                'db_table': 'save_pc_items',
            },
        ),
    ]
