# Generated by Django 4.0 on 2023-01-10 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_savepcitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savepcitems',
            name='category',
        ),
        migrations.AddField(
            model_name='savepcitems',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='save_pc_items_sub_category', to='product.subcategory'),
        ),
    ]
