# Generated by Django 4.0 on 2022-02-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_alter_productreview_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='customer',
        ),
    ]
