# Generated by Django 4.0 on 2023-01-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_savepc_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepcitems',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
