# Generated by Django 4.0 on 2022-02-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_remove_productreview_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='rating_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productreview',
            name='review_text',
            field=models.TextField(default=''),
        ),
    ]
