# Generated by Django 4.0 on 2022-02-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_productreview_rating_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
