# Generated by Django 4.0 on 2023-01-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_savepcitems_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
