# Generated by Django 4.0 on 2023-01-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_brand_meta_description_brand_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
