# Generated by Django 4.0 on 2022-02-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_productreview_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='customer',
        ),
    ]
