# Generated by Django 4.0 on 2023-01-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_alter_product_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashdealproduct',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
