# Generated by Django 4.0 on 2023-01-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_flashdealproduct_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashdealproduct',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='flashdealinfo',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
