# Generated by Django 4.0 on 2023-01-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_remove_flashdealproduct_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingclass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
