# Generated by Django 4.0 on 2022-02-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_product_product_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_child_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_category', to='product.productchildcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='product.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_category', to='product.productsubcategory'),
        ),
    ]
