# Generated by Django 4.0 on 2023-01-24 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', help_text='name', max_length=100)),
                ('ordering_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'OfferCategory',
                'verbose_name_plural': 'OfferCategories',
                'db_table': 'offer_category',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='offers')),
                ('short_description', models.CharField(blank=True, default='', max_length=800, null=True)),
                ('full_description', models.TextField(blank=True, default='', null=True)),
                ('discount_price', models.FloatField(blank=True, default=0, max_length=255, null=True)),
                ('discount_price_type', models.CharField(blank=True, choices=[('per', 'Percentage'), ('flat', 'Flat')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('offer_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Offer_category', to='product.offercategory')),
                ('product', models.ManyToManyField(to='product.Product')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'offer',
            },
        ),
    ]
