# Generated by Django 4.0 on 2022-07-03 12:39

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_attributes_brand_category_discounttypes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCombinationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='products', validators=[product.models.ProductCombinationMedia.validate_file_extension])),
                ('status', models.CharField(choices=[('COMPLETE', 'Complete'), ('IN_QUEUE', 'In_Queue'), ('IN_PROCESSING', 'In_Processing')], default='COMPLETE', max_length=20)),
                ('product_combination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_media_product_combination', to='product.productcombinations')),
            ],
            options={
                'verbose_name': 'ProductCombinationMedia',
                'verbose_name_plural': 'ProductCombinationMedias',
                'db_table': 'product_combination_medias',
            },
        ),
    ]
