# Generated by Django 4.0 on 2022-07-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_productcombinationmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'VariantType',
                'verbose_name_plural': 'VariantTypes',
                'db_table': 'variant_types',
            },
        ),
        migrations.CreateModel(
            name='ProductCombinationsVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_value', models.CharField(max_length=500)),
                ('variant_price', models.FloatField(default=0, max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('discount_amount', models.FloatField(blank=True, default=0, max_length=255, null=True)),
                ('discount_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_combinations_variant_discount_type', to='product.discounttypes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_combinations_variant_product', to='product.product')),
                ('product_combination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_combinations_variant_product_combination', to='product.productcombinations')),
                ('variant_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_combinations_variant_variant_type', to='product.varianttype')),
            ],
            options={
                'verbose_name': 'ProductCombinationsVariant',
                'verbose_name_plural': 'ProductCombinationsVariants',
                'db_table': 'product_combinations_variant',
            },
        ),
    ]
