# Generated by Django 4.0 on 2022-06-27 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_category_cover_category_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcombinations',
            name='product_attribute_values',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_attributes_values', to='product.productattributesvalues'),
        ),
    ]
