# Generated by Django 4.0 on 2022-06-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_productcombinations_product_attribute_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
