# Generated by Django 4.0 on 2022-07-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_varianttype_productcombinationsvariants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolors',
            name='color',
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
    ]
