# Generated by Django 4.0 on 2023-01-24 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_alter_offer_end_date_alter_offer_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_product_category', to='product.category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Offer_offer_category', to='product.offercategory'),
        ),
    ]
