# Generated by Django 4.0 on 2022-07-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_remove_productcolors_color_delete_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcombinations',
            name='product_color',
        ),
        migrations.DeleteModel(
            name='ProductColors',
        ),
    ]
