# Generated by Django 4.0 on 2022-06-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_productreview_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('IN_QUEUE', 'In_Queue'), ('IN_PROCESSING', 'In_Processing')], default='COMPLETE', max_length=20),
        ),
    ]
