# Generated by Django 4.0 on 2022-07-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_remove_productcombinations_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributes',
            name='attribute',
        ),
        migrations.DeleteModel(
            name='Attributes',
        ),
    ]
