# Generated by Django 4.0 on 2022-06-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_alter_productmedia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='color_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcombinations',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
