# Generated by Django 4.0 on 2023-01-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_offer_product_category_alter_offer_offer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_offer_category', to='product.offercategory'),
        ),
    ]
