# Generated by Django 4.0 on 2022-07-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_remove_productattributes_attribute_delete_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcombinations',
            name='product_attribute_values',
        ),
        migrations.DeleteModel(
            name='ProductAttributesValues',
        ),
    ]
