# Generated by Django 4.0 on 2022-06-27 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_colors_color_code_productcombinations_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcombinations',
            name='product_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_combinations_product_color', to='product.productcolors'),
        ),
    ]
