# Generated by Django 4.0 on 2022-06-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_alter_productcombinations_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcombinations',
            name='product_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_combinations_product_attributes', to='product.productattributes'),
        ),
        migrations.AlterField(
            model_name='productcombinations',
            name='product_attribute_values',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_combinations_product_attributes_values', to='product.productattributesvalues'),
        ),
    ]
