# Generated by Django 4.0 on 2022-07-04 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_sub_category_category', to='product.category'),
        ),
    ]
