# Generated by Django 4.0 on 2022-06-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_alter_productcombinations_product_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcombinations',
            name='sku',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
