# Generated by Django 4.0 on 2022-06-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_alter_productcombinations_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sell_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
