# Generated by Django 4.0 on 2022-07-04 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_alter_subsubcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubcategory',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_sub_category_sub_category', to='product.subcategory'),
        ),
    ]
