# Generated by Django 4.0 on 2022-06-29 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_product_sell_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcombinations',
            name='discount_amount',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcombinations',
            name='discount_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_combinations_discount_type', to='product.discounttypes'),
        ),
    ]
