# Generated by Django 4.0 on 2022-07-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_alter_subsubcategory_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=500, null=True, unique=True),
        ),
    ]
