# Generated by Django 4.0 on 2023-01-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_offer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
