# Generated by Django 4.0 on 2022-06-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_productcombinations_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', max_length=500),
        ),
    ]
