# Generated by Django 4.0 on 2022-07-04 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0013_storesettings'),
        ('product', '0057_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_vendor', to='vendor.vendor'),
        ),
    ]
