# Generated by Django 4.0 on 2023-01-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_offerproduct_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount_price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offer_discount_type', to='product.discounttypes'),
        ),
    ]
