# Generated by Django 4.0 on 2023-01-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_alter_offer_discount_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='rating_number',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
