# Generated by Django 4.0 on 2022-06-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0059_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcombinations',
            name='sku',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
