# Generated by Django 4.0 on 2023-01-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_brand_rating_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ShippingCountry',
                'verbose_name_plural': 'ShippingCountries',
                'db_table': 'shipping_country',
            },
        ),
    ]
