# Generated by Django 4.0 on 2023-01-29 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_shippingcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('shipping_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_state_shipping_country', to='product.shippingcountry')),
            ],
            options={
                'verbose_name': 'ShippingState',
                'verbose_name_plural': 'ShippingStates',
                'db_table': 'shipping_state',
            },
        ),
        migrations.CreateModel(
            name='ShippingCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('shipping_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_city_shipping_state', to='product.shippingstate')),
            ],
            options={
                'verbose_name': 'ShippingCity',
                'verbose_name_plural': 'ShippingCities',
                'db_table': 'shipping_city',
            },
        ),
    ]
