# Generated by Django 4.0 on 2023-01-29 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0062_shippingstate_shippingcity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingclass',
            name='title',
        ),
        migrations.AddField(
            model_name='shippingclass',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingclass',
            name='shipping_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_class_shipping_city', to='product.shippingcity'),
        ),
        migrations.AddField(
            model_name='shippingclass',
            name='shipping_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_class_shipping_country', to='product.shippingcountry'),
        ),
        migrations.AddField(
            model_name='shippingclass',
            name='shipping_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_class_shipping_state', to='product.shippingstate'),
        ),
        migrations.AddField(
            model_name='shippingclass',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
