# Generated by Django 4.0 on 2023-01-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0063_remove_shippingclass_title_shippingclass_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_class',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_time',
        ),
    ]
