# Generated by Django 4.0 on 2023-01-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_remove_product_shipping_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingclass',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingclass',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
