# Generated by Django 4.0 on 2022-07-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0064_alter_product_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributes',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
