# Generated by Django 4.0 on 2022-07-04 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0065_productattributes_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributes',
            name='product',
        ),
    ]
