# Generated by Django 4.0 on 2022-07-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_remove_productattributes_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcombinations',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='productcombinations',
            name='discount_type',
        ),
        migrations.AlterField(
            model_name='productcombinations',
            name='sku',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
