# Generated by Django 4.0 on 2023-01-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_remove_shippingstate_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingclass',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='shippingclass',
            name='start_date',
        ),
        migrations.AddField(
            model_name='shippingclass',
            name='delivery_days',
            field=models.IntegerField(default=0, help_text='Minimum days to delivery'),
        ),
    ]
