# Generated by Django 4.0 on 2022-07-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0067_remove_productcombinations_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcombinations',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productcombinations',
            name='varient',
        ),
        migrations.RemoveField(
            model_name='productcombinations',
            name='varient_price',
        ),
    ]
