# Generated by Django 4.0 on 2023-02-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_subcategory_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='is_featured',
        ),
    ]
