# Generated by Django 4.0 on 2022-07-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_subscription'),
        ('product', '0069_productcombinations_product_attribute_color_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='type',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='video_type',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_review_user', to='user.user'),
        ),
    ]
