# Generated by Django 4.0 on 2022-07-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0070_remove_productmedia_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brand'),
        ),
    ]
