# Generated by Django 4.0 on 2022-07-04 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_brand_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcombinationsvariants',
            name='variant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_combinations_variant_variant_type', to='product.varianttype'),
        ),
    ]
