# Generated by Django 4.0 on 2022-07-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0072_alter_productcombinationsvariants_variant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcombinations',
            name='product_attribute_color_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
