# Generated by Django 4.0 on 2023-04-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0074_alter_offer_end_date_alter_offer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashdealinfo',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flashdealinfo',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_end_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
