# Generated by Django 4.0 on 2022-07-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0074_alter_productcombinations_product_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcombinations',
            name='sku',
        ),
        migrations.AddField(
            model_name='productcombinationsvariants',
            name='sku',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
