# Generated by Django 4.0 on 2022-07-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0075_remove_productcombinations_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcombinationsvariants',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
