# Generated by Django 4.0 on 2022-07-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_productcombinationsvariants_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcombinationsvariants',
            name='product',
        ),
    ]
