# Generated by Django 4.0 on 2023-04-13 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_alter_filterattributes_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilterattributes',
            name='attribute_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_filter_attributes_attribute_value', to='product.attributevalues'),
        ),
        migrations.AlterField(
            model_name='productfilterattributes',
            name='filter_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_filter_attributes_filter_attribute', to='product.filterattributes'),
        ),
        migrations.AlterField(
            model_name='productfilterattributes',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_filter_attributes_product', to='product.product'),
        ),
    ]
