# Generated by Django 4.0 on 2022-07-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_remove_productcombinationsvariants_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='old_price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, max_length=255),
        ),
    ]
