# Generated by Django 4.0 on 2022-07-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0078_rename_unit_price_product_old_price_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.TextField(default=''),
        ),
    ]
