# Generated by Django 4.0 on 2023-05-08 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_is_vendor_user_is_seller'),
        ('product', '0079_alter_filterattributes_attribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_text', models.TextField(blank=True, default='', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_review_reply_review', to='product.productreview')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_review_reply_user', to='user.user')),
            ],
            options={
                'verbose_name': 'ProductReviewReply',
                'verbose_name_plural': 'ProductReviewsReply',
                'db_table': 'product_review_reply',
            },
        ),
    ]
