# Generated by Django 4.0 on 2022-09-09 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0079_category_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcombinations',
            name='product_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_combinations_product_attributes', to='product.productattributes'),
        ),
    ]
