# Generated by Django 4.0 on 2022-09-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0080_alter_productcombinations_product_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcombinationsvariants',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productcombinationsvariants',
            name='variant_price',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productcombinationsvariants',
            name='variant_value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
