# Generated by Django 4.0 on 2022-09-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_alter_productcombinationsvariants_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcombinationsvariants',
            name='product_combination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_combinations_variant_product_combination', to='product.productcombinations'),
        ),
        migrations.AlterField(
            model_name='productcombinationsvariants',
            name='variant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_combinations_variant_variant_type', to='product.varianttype'),
        ),
    ]
