# Generated by Django 4.0 on 2023-05-17 10:01

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_categoryimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimages',
            name='file',
            field=models.FileField(upload_to='category_images', validators=[product.models.CategoryImages.validate_file_extension]),
        ),
    ]
