# Generated by Django 4.0 on 2022-09-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0082_alter_productcombinationsvariants_product_combination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcombinationsvariants',
            name='sku',
        ),
    ]
