# Generated by Django 4.0 on 2022-09-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0083_remove_productcombinationsvariants_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcombinationsvariants',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_combinations_variant_product', to='product.product'),
        ),
    ]
