# Generated by Django 4.0 on 2022-09-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0084_productcombinationsvariants_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
