# Generated by Django 4.0 on 2022-09-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0085_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
