# Generated by Django 4.0 on 2022-09-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0088_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttags',
            name='title',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
