# Generated by Django 4.0 on 2022-09-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0089_alter_producttags_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
