# Generated by Django 4.0 on 2022-09-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0091_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REMOVE', 'Remove')], default='PENDING', max_length=20),
        ),
    ]
