# Generated by Django 4.0 on 2022-09-21 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0094_remove_producttags_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttags',
            name='tag',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_tags_product', to='product.tags'),
        ),
    ]
