# Generated by Django 4.0 on 2022-09-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0095_producttags_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcombinations',
            name='product_attribute_price',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
