# Generated by Django 4.0 on 2022-10-19 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0097_productvideoprovider_vattype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=800)),
            ],
            options={
                'verbose_name': 'ProductCondition',
                'verbose_name_plural': 'ProductConditions',
                'db_table': 'product_condition',
            },
        ),
        migrations.CreateModel(
            name='ShippingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=800)),
                ('description', models.TextField(default='')),
                ('delivery_charge', models.FloatField(default=0, max_length=255)),
            ],
            options={
                'verbose_name': 'ShippingClass',
                'verbose_name_plural': 'ShippingClasses',
                'db_table': 'shipping_class',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_vat_type', to='product.vattype'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_product_condition', to='product.productcondition'),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_shipping_class', to='product.shippingclass'),
        ),
    ]
