# Generated by Django 4.0 on 2022-10-19 09:09

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0020_alter_vendor_banner_alter_vendor_logo'),
        ('product', '0098_productcondition_shippingclass_product_vat_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', help_text='name', max_length=100)),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
                'db_table': 'attribute',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', help_text='name', max_length=800)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specification_product', to='product.product')),
            ],
            options={
                'verbose_name': 'Specification',
                'verbose_name_plural': 'Specifications',
                'db_table': 'specification',
            },
        ),
        migrations.RemoveField(
            model_name='productcondition',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productvideoprovider',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shippingclass',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vattype',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='product_category'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='product_category'),
        ),
        migrations.AddField(
            model_name='category',
            name='ordering_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_attributes_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='productcondition',
            name='title',
            field=models.CharField(default='', help_text='name', max_length=800),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_review_vendor', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='productvideoprovider',
            name='title',
            field=models.CharField(default='', help_text='name', max_length=800),
        ),
        migrations.AddField(
            model_name='shippingclass',
            name='title',
            field=models.CharField(default='', help_text='name', max_length=800),
        ),
        migrations.AddField(
            model_name='tags',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tags_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='vattype',
            name='title',
            field=models.CharField(default='', help_text='name', max_length=800),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='', help_text='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_media_product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_review_product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(default='', help_text='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='title',
            field=models.CharField(default='', help_text='name', max_length=100),
        ),
        migrations.CreateModel(
            name='SpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='', max_length=800)),
                ('value', models.CharField(default='', max_length=255)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specification_specification', to='product.specification')),
            ],
            options={
                'verbose_name': 'SpecificationValue',
                'verbose_name_plural': 'SpecificationValues',
                'db_table': 'specification_value',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='products', validators=[product.models.ProductImages.validate_file_extension])),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_images_product', to='product.product')),
            ],
            options={
                'verbose_name': 'ProductImage',
                'verbose_name_plural': 'ProductImages',
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='AttributeValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(default='', max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_values_attribute', to='product.attribute')),
            ],
            options={
                'verbose_name': 'AttributeValues',
                'verbose_name_plural': 'AttributeValues',
                'db_table': 'attribute_attribute',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='filtering_attributes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_filtering_attributes', to='product.attribute'),
        ),
        migrations.AddField(
            model_name='productattributes',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_attributes_attribute', to='product.attribute'),
        ),
    ]
