# Generated by Django 4.0 on 2022-10-19 09:38

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0099_attribute_specification_remove_productcondition_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('color_code', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name': 'ProductColor',
                'verbose_name_plural': 'ProductColors',
                'db_table': 'product_color',
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variation', models.CharField(default='', max_length=255)),
                ('variation_price', models.FloatField(default=0)),
                ('sku', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.FileField(upload_to='product_variation', validators=[product.models.ProductVariation.validate_file_extension])),
                ('total_quantity', models.IntegerField(default=0)),
                ('product_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_variation_product_attribute', to='product.productattributes')),
                ('product_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_variation_color', to='product.productcolor')),
            ],
            options={
                'verbose_name': 'ProductVariation',
                'verbose_name_plural': 'ProductVariations',
                'db_table': 'product_variation',
            },
        ),
    ]
