# Generated by Django 4.0 on 2022-10-19 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0020_alter_vendor_banner_alter_vendor_logo'),
        ('product', '0100_productcolor_productvariation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_vendor', to='vendor.vendor'),
        ),
    ]
