# Generated by Django 4.0 on 2022-10-19 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0104_attribute_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalues',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ProductAttributeValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_attribute_values_product_attribute', to='product.productattributes')),
            ],
            options={
                'verbose_name': 'ProductAttributeValue',
                'verbose_name_plural': 'ProductAttributeValues',
                'db_table': 'product_attribute_value',
            },
        ),
    ]
