# Generated by Django 4.0 on 2022-10-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0105_attributevalues_is_active_productattributevalues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='product_attribute',
        ),
    ]
