# Generated by Django 4.0 on 2022-10-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0107_remove_productvariation_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
