# Generated by Django 4.0 on 2022-10-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0109_inventory_productvariation_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='is_published',
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
