# Generated by Django 4.0 on 2022-10-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0110_remove_productreview_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvideoprovider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
