# Generated by Django 4.0 on 2022-10-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0113_specification_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vattype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
