# Generated by Django 4.0 on 2022-10-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0114_vattype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashdealinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flashdealproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
