# Generated by Django 4.0 on 2022-10-23 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0116_productattributevalues_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationvalue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specificationvalue',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specification_value_product', to='product.product'),
        ),
    ]
