# Generated by Django 4.0 on 2022-10-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0117_specificationvalue_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcolor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
