# Generated by Django 4.0 on 2022-10-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0117_specificationvalue_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_house_product',
            field=models.BooleanField(default=True),
        ),
    ]
