# Generated by Django 4.0 on 2022-10-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0118_textcolor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
