# Generated by Django 4.0 on 2022-10-26 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0118_remove_tags_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='image',
            new_name='file',
        ),
        migrations.AddField(
            model_name='productimages',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productimages',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('IN_QUEUE', 'In_Queue'), ('IN_PROCESSING', 'In_Processing')], default='COMPLETE', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISH', 'Publish'), ('UNPUBLISH', 'UnPublish')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_image_product', to='product.product'),
        ),
    ]
