# Generated by Django 4.0 on 2022-10-26 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0119_rename_image_productimages_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalues',
            name='product_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_attribute_values_product_attribute', to='product.productattributes'),
        ),
    ]
