# Generated by Django 4.0 on 2022-10-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0119_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='ordering_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subsubcategory',
            name='ordering_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='', help_text='name', max_length=100),
        ),
    ]
