# Generated by Django 4.0 on 2022-10-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0120_alter_productattributevalues_product_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributes',
            name='title',
        ),
    ]
