# Generated by Django 4.0 on 2022-10-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0120_alter_brand_title'),
        ('product', '0120_subcategory_ordering_number_and_more'),
    ]

    operations = [
    ]
