# Generated by Django 4.0 on 2022-10-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0121_merge_20221026_1253'),
        ('product', '0121_remove_productattributes_title'),
    ]

    operations = [
    ]
