# Generated by Django 4.0 on 2022-10-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0122_merge_20221026_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subtitle',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
