# Generated by Django 4.0 on 2022-10-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0123_alter_category_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ordering_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='ordering_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='ordering_number',
            field=models.IntegerField(default=0),
        ),
    ]
