# Generated by Django 4.0 on 2022-10-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0125_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='total_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='variation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='variation_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
