# Generated by Django 4.0 on 2022-10-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0127_remove_productvariation_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryvariation',
            name='product_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_variation_product_variation', to='product.productvariation'),
        ),
    ]
