# Generated by Django 4.0 on 2022-10-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0128_inventoryvariation_product_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='current_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='initial_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
