# Generated by Django 4.0 on 2022-10-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0130_alter_inventoryvariation_inventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryVariation',
            new_name='InventoryVariationManage',
        ),
        migrations.AlterModelOptions(
            name='inventoryvariationmanage',
            options={'verbose_name': 'InventoryVariationManage', 'verbose_name_plural': 'InventoryVariationManages'},
        ),
        migrations.AlterModelTable(
            name='inventoryvariationmanage',
            table='inventory_variation_manage',
        ),
    ]
