# Generated by Django 4.0 on 2022-10-27 15:30

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0131_rename_inventoryvariation_inventoryvariationmanage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryvariationmanage',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_variation_manage_inventory', to='product.inventory'),
        ),
        migrations.AlterField(
            model_name='inventoryvariationmanage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_variation_manage_product', to='product.product'),
        ),
        migrations.AlterField(
            model_name='inventoryvariationmanage',
            name='product_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_variation_manage_product_variation', to='product.productvariation'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product_variation', validators=[product.models.ProductVariation.validate_file_extension]),
        ),
    ]
