# Generated by Django 4.0 on 2022-10-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0134_inventoryvariation_delete_inventoryvariationmanage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryvariation',
            name='inventory',
        ),
    ]
