# Generated by Django 4.0 on 2022-10-27 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0135_remove_inventoryvariation_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashdealinfo',
            name='background_color',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flashdealinfo',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flashdealinfo',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
