# Generated by Django 4.0 on 2022-10-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0137_alter_flashdealinfo_text_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashdealproduct',
            name='flashDealInfo',
        ),
        migrations.AddField(
            model_name='flashdealproduct',
            name='flash_deal_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flash_deal_product_flash_deal_info', to='product.flashdealinfo'),
        ),
        migrations.AlterField(
            model_name='flashdealproduct',
            name='discount_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flash_deal_product_discount_type', to='product.discounttypes'),
        ),
    ]
