# Generated by Django 4.0 on 2022-11-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0036_seller_is_active'),
        ('product', '0140_remove_product_vendor_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_vendor', to='vendor.vendor'),
        ),
    ]
