# Generated by Django 4.0 on 2022-11-09 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0141_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_house_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productattributevalues',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_attribute_values_value', to='product.attributevalues'),
        ),
    ]
