# Generated by Django 4.0 on 2022-11-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0142_alter_product_in_house_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
    ]
