# Generated by Django 4.0 on 2022-11-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0143_remove_product_warranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_price',
        ),
    ]
