# Generated by Django 4.0 on 2022-11-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0144_remove_product_old_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_cost_multiply',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_in_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_shipping_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='youtube_link',
        ),
    ]
