# Generated by Django 4.0 on 2022-11-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0145_remove_product_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
