# Generated by Django 4.0 on 2022-11-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0146_remove_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='file',
        ),
    ]
