# Generated by Django 4.0 on 2022-11-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0147_remove_productmedia_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmedia',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='status',
        ),
    ]
