# Generated by Django 4.0 on 2022-11-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0148_remove_productmedia_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_media_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'Complete'), ('IN_QUEUE', 'In_Queue'), ('IN_PROCESSING', 'In_Processing')], default='COMPLETE', max_length=20),
        ),
    ]
