# Generated by Django 4.0 on 2022-11-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0149_productmedia_is_active_productmedia_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='filtering_attributes',
        ),
        migrations.AddField(
            model_name='category',
            name='filtering_attributes',
            field=models.ManyToManyField(to='product.Attribute'),
        ),
    ]
