# Generated by Django 4.0 on 2022-11-13 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0150_remove_category_filtering_attributes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='filtering_attributes',
        ),
        migrations.AddField(
            model_name='category',
            name='filtering_attributes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_filtering_attributes', to='product.attribute'),
        ),
    ]
