# Generated by Django 4.0 on 2022-11-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0151_remove_category_filtering_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFilterAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_filter_attributes_attribute', to='product.attribute')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_filter_attributes_category', to='product.category')),
            ],
            options={
                'verbose_name': 'CategoryFilterAttribute',
                'verbose_name_plural': 'CategoryFilterAttributes',
                'db_table': 'category_filter_attributes',
            },
        ),
    ]
