# Generated by Django 4.0 on 2022-11-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0142_alter_product_in_house_product'),
        ('product', '0152_categoryfilterattributes'),
    ]

    operations = [
    ]
