# Generated by Django 4.0 on 2022-11-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0153_merge_20221114_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='filtering_attributes',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='total_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
