# Generated by Django 4.0 on 2022-11-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0153_merge_20221114_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='filtering_attributes',
        ),
    ]
