# Generated by Django 4.0 on 2022-11-15 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0153_merge_20221114_1213'),
        ('product', '0154_remove_category_filtering_attributes_and_more'),
    ]

    operations = [
    ]
