# Generated by Django 4.0 on 2022-11-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0156_specificationtitle_alter_specification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='title',
            field=models.CharField(default='', help_text='name', max_length=800),
        ),
    ]
