# Generated by Django 4.0 on 2022-11-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0157_alter_specification_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecificationTitle',
        ),
    ]
