# Generated by Django 4.0 on 2022-11-15 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0158_delete_specificationtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', help_text='name', max_length=800)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SpecificationTitle',
                'verbose_name_plural': 'SpecificationTitles',
                'db_table': 'specification_title',
            },
        ),
        migrations.AlterField(
            model_name='specification',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='specification_specification_title', to='product.specificationtitle'),
        ),
    ]
