# Generated by Django 4.0 on 2022-11-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0160_remove_product_is_gaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_gaming',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
