# Generated by Django 4.0 on 2022-11-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0161_product_is_gaming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_gaming',
        ),
    ]
