# Generated by Django 4.0 on 2022-11-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0155_alter_brand_title'),
        ('product', '0162_remove_product_is_gaming'),
    ]

    operations = [
    ]
