# Generated by Django 4.0 on 2022-11-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('whatsapp_number', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footers',
                'db_table': 'footer',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('whatsapp_number', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Headers',
                'db_table': 'header',
            },
        ),
    ]
