# Generated by Django 4.0 on 2022-11-22 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='name', max_length=100)),
            ],
            options={
                'verbose_name': 'BlogCategory',
                'verbose_name_plural': 'BlogCategories',
                'db_table': 'blog_categories',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='name', max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255)),
                ('full_description', models.TextField()),
                ('short_description', models.CharField(max_length=800)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_category', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'db_table': 'blogs',
            },
        ),
    ]
