# Generated by Django 4.0 on 2022-12-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
