# Generated by Django 4.0 on 2023-01-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_subscription_is_active'),
        ('blog', '0003_blog_is_active_blog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_created_user', to='user.user'),
        ),
        migrations.AddField(
            model_name='blog',
            name='total_average_rating_number',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='view_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='BlogReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_number', models.FloatField(blank=True, default=0.0, null=True)),
                ('review_text', models.TextField(blank=True, default='', null=True)),
                ('reviewer_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_review_blog', to='blog.blog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_review_user', to='user.user')),
            ],
            options={
                'verbose_name': 'BlogReview',
                'verbose_name_plural': 'BlogReviews',
                'db_table': 'blog_review',
            },
        ),
    ]
