# Generated by Django 4.0 on 2023-02-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_blog_text_blog_full_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('PUBLISH', 'Publish'), ('UNPUBLISH', 'UnPublish')], default='UnPublish', max_length=20),
        ),
    ]
