# Generated by Django 4.0 on 2022-02-20 06:23

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to='sliderImage', validators=[home.models.SliderImage.validate_file_extension])),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'SliderImage',
                'verbose_name_plural': 'SliderImages',
                'db_table': 'sliderImages',
            },
        ),
    ]
