# Generated by Django 4.0 on 2022-12-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderimage',
            old_name='text',
            new_name='bold_text',
        ),
        migrations.RenameField(
            model_name='sliderimage',
            old_name='background_img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='sliderimage',
            name='static_img',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='small_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
