# Generated by Django 4.0 on 2022-02-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
