# Generated by Django 4.0 on 2023-01-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_text_sliderimage_bold_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSingleRowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whats_app_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bottom_banner', models.ImageField(default='', upload_to='sliderImage')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'HomeSingleRowData',
                'verbose_name_plural': 'HomeSingleRowDatas',
                'db_table': 'home_single_row_data',
            },
        ),
    ]
