# Generated by Django 4.0 on 2022-02-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sliderimage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
