# Generated by Django 4.0 on 2023-01-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homesinglerowdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProductsUnderPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='', upload_to='HomeImage')),
                ('bold_text', models.TextField(blank=True, null=True)),
                ('small_text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FeaturedProductsUnderPoster',
                'verbose_name_plural': 'FeaturedProductsUnderPosters',
                'db_table': 'featured_products_under_poster',
            },
        ),
        migrations.CreateModel(
            name='PopularProductsUnderPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='', upload_to='HomeImage')),
                ('bold_text', models.TextField(blank=True, null=True)),
                ('small_text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PopularProductsUnderPoster',
                'verbose_name_plural': 'PopularProductsUnderPosters',
                'db_table': 'popular_products_under_poster',
            },
        ),
        migrations.CreateModel(
            name='PosterUnderSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='', upload_to='HomeImage')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PosterUnderSlider',
                'verbose_name_plural': 'PosterUnderSliders',
                'db_table': 'poster_under_slider',
            },
        ),
        migrations.AlterField(
            model_name='homesinglerowdata',
            name='bottom_banner',
            field=models.ImageField(default='', upload_to='HomeImage'),
        ),
    ]
