# Generated by Django 4.0 on 2022-02-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_product_slug'),
        ('home', '0003_sliderimage_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealsOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('discount_price', models.FloatField(default=0, max_length=255)),
                ('discount_price_type', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'DealsOfTheDay',
                'verbose_name_plural': 'DealsOfTheDays',
                'db_table': 'dealsOfTheDay',
            },
        ),
    ]
