# Generated by Django 4.0 on 2022-02-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_product_slug'),
        ('home', '0004_dealsoftheday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsoftheday',
            name='discount_price_type',
            field=models.CharField(choices=[('per', 'Percentage'), ('flat', 'Flat')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='dealsoftheday',
            name='product',
        ),
        migrations.AddField(
            model_name='dealsoftheday',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
