# Generated by Django 4.0 on 2023-01-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactus_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='is_gaming',
            field=models.BooleanField(default=True),
        ),
    ]
