# Generated by Django 4.0 on 2022-02-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_dealsoftheday_discount_price_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealsoftheday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
