# Generated by Django 4.0 on 2023-01-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sliderimage_is_gaming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='is_gaming',
            field=models.BooleanField(default=False),
        ),
    ]
