# Generated by Django 4.0 on 2022-02-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_dealsoftheday_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealsoftheday',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealsoftheday',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
