# Generated by Django 4.0 on 2022-02-23 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_productcategory_cover_productcategory_logo'),
        ('user', '0006_subscription'),
        ('home', '0007_alter_dealsoftheday_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_product_view', to='user.customerprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_view_count', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_product_view', to='user.user')),
            ],
            options={
                'verbose_name': 'Product View',
                'verbose_name_plural': 'Product Views',
                'db_table': 'product_views',
            },
        ),
    ]
