# Generated by Django 4.0 on 2023-01-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_sliderimage_is_gaming'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularproductsunderposter',
            name='is_gaming',
            field=models.BooleanField(default=False),
        ),
    ]
