# Generated by Django 4.0 on 2022-02-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_productview_view_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productview',
            name='view_count',
            field=models.IntegerField(default=1),
        ),
    ]
