# Generated by Django 4.0 on 2023-01-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_featuredproductsunderposter_is_gaming'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('details_text', models.TextField(blank=True, null=True)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='corporate')),
            ],
            options={
                'verbose_name': 'CorporateDeal',
                'verbose_name_plural': 'CorporateDeals',
                'db_table': 'corporate_deal',
            },
        ),
    ]
