# Generated by Django 4.0 on 2022-06-30 06:07

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_productview_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimage',
            name='file',
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='background_img',
            field=models.ImageField(default='', upload_to='sliderImage', validators=[home.models.SliderImage.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='static_img',
            field=models.ImageField(default='', upload_to='sliderImage', validators=[home.models.SliderImage.validate_file_extension]),
        ),
    ]
