# Generated by Django 4.0 on 2023-01-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_corporatedeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatedeal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
