# Generated by Django 4.0 on 2023-01-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_corporatedeal_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DealsOfTheDay',
        ),
    ]
