# Generated by Django 4.0 on 2023-02-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_requestquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='', upload_to='HomeImage')),
                ('bold_text', models.TextField(blank=True, null=True)),
                ('small_text', models.TextField(blank=True, null=True)),
                ('is_gaming', models.BooleanField(default=False)),
                ('work_for', models.CharField(choices=[('SLIDER', 'slider'), ('POPULAR_PRODUCT_POSTER', 'popular_product_poster'), ('FEATURED_PRODUCT_POSTER', 'featured_product_poster')], default='SLIDER', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'db_table': 'advertisement',
            },
        ),
    ]
