# Generated by Django 4.0 on 2023-02-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_advertisement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedProductsUnderPoster',
        ),
        migrations.DeleteModel(
            name='PopularProductsUnderPoster',
        ),
        migrations.DeleteModel(
            name='PosterUnderSlider',
        ),
    ]
