# Generated by Django 4.0 on 2023-02-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_featuredproductsunderposter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatedeal',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
