# Generated by Django 4.0 on 2023-02-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_advertisement_work_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='work_for',
            field=models.CharField(choices=[('SLIDER', 'slider'), ('SLIDER_SMALL', 'slider_small'), ('POPULAR_PRODUCT_POSTER', 'popular_product_poster'), ('FEATURED_PRODUCT_POSTER', 'featured_product_poster')], default='SLIDER', max_length=30),
        ),
    ]
