# Generated by Django 4.0 on 2023-02-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_advertisement_work_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestquote',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
