# Generated by Django 4.0 on 2023-04-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_advertisement_work_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='work_for',
            field=models.CharField(choices=[('SLIDER', 'slider'), ('SLIDER_SMALL_CAROUSEL', 'slider_small_carousel'), ('SLIDER_SMALL_STATIC', 'slider_small_static'), ('POPULAR_PRODUCT_POSTER', 'popular_product_poster'), ('FEATURED_PRODUCT_POSTER', 'featured_product_poster'), ('GAMING_POPULAR_PRODUCT_POSTER', 'gaming_popular_product_poster'), ('GAMING_FEATURED_PRODUCT_POSTER', 'gaming_featured_product_poster')], default='SLIDER', max_length=30),
        ),
    ]
