# Generated by Django 4.0 on 2023-05-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_pages_alter_advertisement_work_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='page_title',
            field=models.CharField(default='', max_length=800),
        ),
    ]
