# Generated by Django 4.0 on 2023-05-10 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_pages_page_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='page_title',
            new_name='title',
        ),
    ]
