# Generated by Django 4.0 on 2023-05-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_mediafiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media_files'),
        ),
    ]
