# Generated by Django 4.0 on 2023-05-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_mediafiles_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafiles',
            name='title',
            field=models.CharField(default='', max_length=800),
        ),
    ]
