# Generated by Django 4.0 on 2023-05-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_mediafiles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafiles',
            name='title',
            field=models.CharField(blank=True, default='', max_length=800, null=True),
        ),
    ]
