# Generated by Django 4.0 on 2023-05-10 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_mediafiles_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=800, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'MediaChunk',
                'verbose_name_plural': 'MediaChunks',
                'db_table': 'media_chunks',
            },
        ),
        migrations.AddField(
            model_name='mediafiles',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files_chunk', to='home.mediachunk'),
        ),
    ]
