# Generated by Django 4.0 on 2023-05-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_aboutus_promise_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesinglerowdata',
            name='bottom_banner_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
