# Generated by Django 4.0 on 2022-11-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_attribute',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_varient',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variation',
        ),
    ]
