# Generated by Django 4.0 on 2022-01-30 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customerprofile_options_and_more'),
        ('cart', '0006_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items_user', to='user.user'),
        ),
    ]
