# Generated by Django 4.0 on 2022-11-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_coupon_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='type_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
