# Generated by Django 4.0 on 2022-02-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_billingaddress_apartment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
