# Generated by Django 4.0 on 2022-11-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_paymenttype_type_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttype',
            name='type_key',
        ),
    ]
