# Generated by Django 4.0 on 2022-02-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_order_full_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_description',
            new_name='notes',
        ),
    ]
