# Generated by Django 4.0 on 2022-02-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_rename_full_description_order_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
            options={
                'verbose_name': 'PaymentType',
                'verbose_name_plural': 'PaymentTypes',
                'db_table': 'payment_types',
            },
        ),
    ]
