# Generated by Django 4.0 on 2022-02-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_paymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
