# Generated by Django 4.0 on 2022-02-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
