# Generated by Django 4.0 on 2022-02-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_shippingtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingtype',
            name='slug',
        ),
    ]
