# Generated by Django 4.0 on 2022-02-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_remove_shippingtype_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttype',
            name='slug',
        ),
    ]
