# Generated by Django 4.0 on 2022-02-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_remove_paymenttype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingtype',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
