# Generated by Django 4.0 on 2022-02-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_order_shipping_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
