# Generated by Django 4.0 on 2022-12-27 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_category_is_gaming_remove_product_is_gaming'),
        ('cart', '0021_remove_order_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_product', to='product.product'),
        ),
    ]
