# Generated by Django 4.0 on 2022-12-27 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_alter_wishlist_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Wishlist', 'verbose_name_plural': 'Wishlists'},
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table='wishlist',
        ),
    ]
