# Generated by Django 4.0 on 2023-01-04 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_delete_vendororder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItemCombination',
        ),
    ]
