# Generated by Django 4.0 on 2023-01-08 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_productwarranty_product_productwarranty_warranty'),
        ('cart', '0026_orderitem_warranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='warranty',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_after_add_warranty',
            field=models.FloatField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_warranty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_product_warranty', to='product.productwarranty'),
        ),
    ]
