# Generated by Django 4.0 on 2023-01-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_remove_orderitem_warranty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_after_add_warranty',
            new_name='unit_price_after_add_warranty',
        ),
    ]
