# Generated by Django 4.0 on 2022-02-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_remove_order_billing_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAddress',
            new_name='CustomerAddress',
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'verbose_name': 'CustomerAddress', 'verbose_name_plural': 'CustomerAddresses'},
        ),
        migrations.AlterModelTable(
            name='customeraddress',
            table='customer_addresses',
        ),
    ]
