# Generated by Django 4.0 on 2022-02-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_rename_billingaddress_customeraddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='address_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
