# Generated by Django 4.0 on 2023-01-15 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_suborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sub_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_sub_order', to='cart.suborder'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='in_house_order',
            field=models.BooleanField(default=False),
        ),
    ]
