# Generated by Django 4.0 on 2023-01-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_orderitem_sub_order_suborder_in_house_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suborder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
