# Generated by Django 4.0 on 2023-02-01 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_alter_shippingclass_shipping_city_and_more'),
        ('cart', '0032_order_in_house_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='shipping_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.shippingclass'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='shipping_cost',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
