# Generated by Django 4.0 on 2022-04-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0033_order_discounted_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together={('code',)},
        ),
    ]
