# Generated by Django 4.0 on 2023-02-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0033_deliveryaddress_shipping_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_type',
        ),
    ]
