# Generated by Django 4.0 on 2022-06-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0034_alter_coupon_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('PROCESSING', 'processing'), ('SHIPPED', 'shipped'), ('DELIVERED', 'delivered'), ('RETURN', 'return'), ('CANCEL', 'cancel')], default='processing', max_length=20),
        ),
    ]
