# Generated by Django 4.0 on 2023-02-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0034_remove_coupon_coupon_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_type',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='title', max_length=15),
        ),
    ]
