# Generated by Django 4.0 on 2023-02-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0035_remove_coupon_discount_type_alter_coupon_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='min_shopping',
            new_name='min_shopping_amount',
        ),
    ]
