# Generated by Django 4.0 on 2023-02-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0036_rename_min_shopping_coupon_min_shopping_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='min_shopping_amount',
            field=models.IntegerField(default=0),
        ),
    ]
