# Generated by Django 4.0 on 2022-06-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0037_userecordofcoupon_delete_userecordofcupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userecordofcoupon',
            options={'verbose_name': 'UseRecordOfCoupon', 'verbose_name_plural': 'UseRecordOfCoupons'},
        ),
        migrations.AlterModelTable(
            name='userecordofcoupon',
            table='use_record_o_coupon',
        ),
    ]
