# Generated by Django 4.0 on 2023-02-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0037_alter_coupon_min_shopping_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=0, help_text='Amount Coupon', max_length=255),
        ),
    ]
