# Generated by Django 4.0 on 2022-06-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0038_alter_userecordofcoupon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userecordofcoupon',
            table='use_record_of_coupon',
        ),
    ]
