# Generated by Django 4.0 on 2023-02-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0034_order_customer'),
        ('cart', '0038_coupon_quantity_alter_coupon_amount'),
    ]

    operations = [
    ]
