# Generated by Django 4.0 on 2023-02-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0039_merge_20230205_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('VAT', 'vat')], default='VAT', max_length=20)),
                ('value', models.FloatField(default=0.0, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Tax',
                'db_table': 'tax',
            },
        ),
    ]
