# Generated by Django 4.0 on 2023-02-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0040_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='value_type',
            field=models.CharField(choices=[('PERCENT', '%')], default='PERCENT', max_length=20),
        ),
    ]
