# Generated by Django 4.0 on 2022-09-25 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_subscription'),
        ('vendor', '0018_alter_storesettings_facebook_and_more'),
        ('cart', '0040_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_customer_profile', to='user.customerprofile'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items_vendor', to='vendor.vendor'),
        ),
    ]
