# Generated by Django 4.0 on 2022-09-25 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_subscription'),
        ('cart', '0041_order_customer_profile_orderitem_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=True)),
                ('being_delivered', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('refund_requested', models.BooleanField(default=False)),
                ('refund_granted', models.BooleanField(default=False)),
                ('order_status', models.CharField(choices=[('PENDING', 'pending'), ('PROCESSING', 'processing'), ('SHIPPED', 'shipped'), ('DELIVERED', 'delivered'), ('RETURN', 'return'), ('CANCEL', 'cancel')], default='processing', max_length=20)),
                ('customer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_order_customer_profile', to='user.customerprofile')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_order_order', to='cart.order')),
                ('shipping_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_order_shipping_type', to='cart.shippingtype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_order_user', to='user.user')),
            ],
            options={
                'verbose_name': 'VendorOrder',
                'verbose_name_plural': 'VendorOrders',
                'db_table': 'vendor_orders',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items_vendor_order', to='cart.vendororder'),
        ),
    ]
