# Generated by Django 4.0 on 2023-02-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0042_alter_order_coupon_discount_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
