# Generated by Django 4.0 on 2022-09-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0018_alter_storesettings_facebook_and_more'),
        ('cart', '0043_remove_vendororder_being_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_order_vendor', to='vendor.vendor'),
        ),
    ]
