# Generated by Django 4.0 on 2023-02-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0043_delete_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax_amount',
            new_name='vat_amount',
        ),
    ]
