# Generated by Django 4.0 on 2023-02-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0044_rename_tax_amount_order_vat_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='number_of_uses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Maximum number of coupon use by the user.'),
        ),
    ]
