# Generated by Django 4.0 on 2022-09-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0044_vendororder_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='slug',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='vendororder',
            old_name='slug',
            new_name='vendor_order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='product_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
