# Generated by Django 4.0 on 2023-02-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0045_alter_coupon_number_of_uses_alter_coupon_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True),
        ),
    ]
