# Generated by Django 4.0 on 2022-09-27 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0095_producttags_tag'),
        ('cart', '0045_rename_slug_order_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_attribute_value', models.CharField(default='', max_length=500)),
                ('product_attribute_color_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('variant_value', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_combination_order', to='cart.order')),
                ('orderItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_combination_order_item', to='cart.orderitem')),
                ('product_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_item_combination_product_attributes', to='product.productattributes')),
                ('variant_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_item_combination_variant_type', to='product.varianttype')),
            ],
            options={
                'verbose_name': 'OrderItemCombination',
                'verbose_name_plural': 'OrderItemCombinations',
                'db_table': 'order_item_combination',
            },
        ),
    ]
