# Generated by Django 4.0 on 2022-09-27 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0047_remove_orderitemcombination_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemcombination',
            name='product_attribute_color_code',
        ),
    ]
