# Generated by Django 4.0 on 2023-02-27 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_subcategory_is_featured'),
        ('cart', '0048_orderitem_offer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_offer', to='product.offer'),
        ),
    ]
