# Generated by Django 4.0 on 2022-09-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0049_remove_orderitemcombination_variant_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemcombination',
            name='variant_price',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
