# Generated by Django 4.0 on 2023-02-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0049_orderitem_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.FloatField(blank=True, default=0.0, max_length=255, null=True),
        ),
    ]
