# Generated by Django 4.0 on 2023-05-29 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0050_order_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='country',
        ),
    ]
