# Generated by Django 4.0 on 2022-09-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0050_orderitemcombination_variant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemcombination',
            name='variant_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
