# Generated by Django 4.0 on 2023-05-29 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0083_categorybannerimages'),
        ('cart', '0051_remove_deliveryaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.shippingcountry'),
        ),
    ]
