# Generated by Django 4.0 on 2022-09-27 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0051_orderitemcombination_variant_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemcombination',
            old_name='variant_quantity',
            new_name='variant_ordered_quantity',
        ),
    ]
