# Generated by Django 4.0 on 2022-09-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0052_rename_variant_quantity_orderitemcombination_variant_ordered_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemcombination',
            name='product',
        ),
    ]
