# Generated by Django 4.0 on 2022-09-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0095_producttags_tag'),
        ('cart', '0053_remove_orderitemcombination_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemcombination',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_combination_product', to='product.product'),
        ),
    ]
