# Generated by Django 4.0 on 2022-09-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0054_orderitemcombination_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemcombination',
            name='product_attribute_price',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
