# Generated by Django 4.0 on 2022-10-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0055_orderitemcombination_product_attribute_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_shopping',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
