# Generated by Django 4.0 on 2022-10-20 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0056_coupon_coupon_type_coupon_min_shopping'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'DiscountType',
                'verbose_name_plural': 'DiscountTypes',
                'db_table': 'discounttype',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discounttype', to='cart.discounttype'),
            preserve_default=False,
        ),
    ]
