# Generated by Django 4.0 on 2022-10-24 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0109_inventory_productvariation_attribute_and_more'),
        ('vendor', '0028_alter_seller_logo'),
        ('cart', '0057_discounttype_coupon_discount_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='being_delivered',
            new_name='cash_on_deliver',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ordered_date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='coupon_status',
            new_name='refund',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_profile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_requested',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_type',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount_amount',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_agent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UN-PAID', 'Un-Paid')], default='Un-Paid', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.shippingclass'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_vendor', to='vendor.seller'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productattributes'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_attribute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_varient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.FloatField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.FloatField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PICKED-UP', 'Picked Up'), ('DELIVERED', 'Delivered'), ('RETURN', 'Return'), ('CANCEL', 'Cancel')], default='Confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items_refund', to='cart.order'),
        ),
    ]
