# Generated by Django 4.0 on 2022-10-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0058_alter_coupon_discount_type_alter_discounttype_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(max_length=255),
        ),
    ]
