# Generated by Django 4.0 on 2022-10-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0059_alter_coupon_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounttype',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
