# Generated by Django 4.0 on 2022-10-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0060_discounttype_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountType',
        ),
    ]
