# Generated by Django 4.0 on 2022-10-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0058_rename_being_delivered_order_cash_on_deliver_and_more'),
        ('cart', '0060_discounttype_is_active'),
    ]

    operations = [
    ]
