# Generated by Django 4.0 on 2022-10-25 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0118_alter_product_in_house_product'),
        ('cart', '0061_merge_20221024_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountType',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor_order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items_variation', to='product.productvariation'),
        ),
    ]
