# Generated by Django 4.0 on 2022-10-23 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0061_delete_discounttype_refund_refund_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_qty', models.IntegerField()),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.orderitem')),
                ('refund_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.refund')),
            ],
            options={
                'verbose_name': 'RefundOrderItem',
                'verbose_name_plural': 'RefundOrderItems',
                'db_table': 'refund_order_item',
            },
        ),
    ]
