# Generated by Django 4.0 on 2022-10-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0061_merge_20221024_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountType',
        ),
    ]
