# Generated by Django 4.0 on 2022-10-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0121_merge_20221026_1253'),
        ('cart', '0061_merge_20221026_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountType',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cash_on_deliver',
            new_name='cash_on_delivery',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor_order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items_variation', to='product.productvariation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UN-PAID', 'Un-Paid'), ('PAID', 'Paid')], default='Paid', max_length=20),
        ),
    ]
