# Generated by Django 4.0 on 2022-10-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0122_merge_20221026_1713'),
        ('cart', '0062_delete_discounttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_type', to='product.discounttypes'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_shopping',
            field=models.FloatField(default=0.0),
        ),
    ]
