# Generated by Django 4.0 on 2022-10-30 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_otpmodel_remove_user_verified_phone'),
        ('cart', '0063_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.deliveryaddress'),
        ),
    ]
