# Generated by Django 4.0 on 2022-12-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_title',
            new_name='ticket_subject',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NOT-RESOLVED', 'Not-Resolved'), ('RESOLVED', 'Resolved')], default='NOT-RESOLVED', max_length=20),
        ),
    ]
