# Generated by Django 4.0 on 2022-12-15 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customerprofile_avatar'),
        ('support_ticket', '0002_rename_ticket_title_ticket_ticket_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_creator_user', to='user.user'),
        ),
        migrations.CreateModel(
            name='TicketConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('replier_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replier_user', to='user.user')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_conversation_ticket', to='support_ticket.ticket')),
            ],
            options={
                'verbose_name': 'TicketConversation',
                'verbose_name_plural': 'ticket_conversations',
                'db_table': 'ticket_conversation',
            },
        ),
    ]
