# Generated by Django 4.0 on 2022-12-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0003_alter_ticket_user_ticketconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issue_photo',
            field=models.FileField(blank=True, null=True, upload_to='ticket_photo'),
        ),
    ]
