# Generated by Django 4.0 on 2022-12-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0005_ticket_ticket_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solution_photo',
            field=models.FileField(blank=True, null=True, upload_to='ticket_photo'),
        ),
    ]
