# Generated by Django 4.0 on 2022-12-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_permissionmodules_rolepermissions'),
        ('user', '0002_customerprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_role_in_user_role', to='stuff.role'),
        ),
    ]
