# Generated by Django 4.0 on 2023-02-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_subscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete_request',
            field=models.BooleanField(default=False),
        ),
    ]
