# Generated by Django 4.0 on 2022-01-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customerprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Customer Profile', 'verbose_name_plural': 'Customer Profile'},
        ),
        migrations.AlterModelTable(
            name='customerprofile',
            table='customer_profiles',
        ),
    ]
