# Generated by Django 4.0 on 2023-04-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_vendor',
            new_name='is_seller',
        ),
    ]
